version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frameit-application-backend
    #environment:
     # - DATABASE_URL=mysql+pymysql://frameit-admin:FrameIt123@mysql_container:3306/frameit
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app_network
    volumes:
      - .:/app  # Mount the current directory for development

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: frameit
      MYSQL_USER: frameit-admin
      MYSQL_PASSWORD: FrameIt123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
volumes:
  db_data:

networks:
  app_network:
