"""Add prompts and agent_configs tables
Revision ID: b197ea52bce4
Revises: Create Date: 2024-12-30 11:23:02.782666
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "b197ea52bce4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompts_id", table_name="prompts")
    op.drop_index("name", table_name="prompts")
    op.drop_table("prompts")
    op.drop_index("ix_agent_configs_id", table_name="agent_configs")
    op.drop_index("name", table_name="agent_configs")
    op.drop_table("agent_configs")
    op.drop_index("ix_themes_id", table_name="themes")
    op.drop_table("themes")
    op.drop_index("ix_agents_id", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_agents_id", "agents", ["id"], unique=False)
    op.create_table(
        "themes",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=512), nullable=True),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_themes_id", "themes", ["id"], unique=False)
    op.create_table(
        "agent_configs",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("model", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("system_prompt", mysql.TEXT(), nullable=False),
        sa.Column("deps_type", mysql.JSON(), nullable=True),
        sa.Column("result_type", mysql.JSON(), nullable=True),
        sa.Column("model_settings", mysql.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("name", "agent_configs", ["name"], unique=True)
    op.create_index("ix_agent_configs_id", "agent_configs", ["id"], unique=False)
    op.create_table(
        "prompts",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("prompt_text", mysql.TEXT(), nullable=False),
        sa.Column("version", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("context", mysql.VARCHAR(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("name", "prompts", ["name"], unique=True)
    op.create_index("ix_prompts_id", "prompts", ["id"], unique=False)
    # ### end Alembic commands ###
